scaleTest_coretran – Fortran Program
scaleTest_coretran Program
238 statements
Source File
Uses:
iso_fortran_env
variableKind
m_array1D
m_errors
m_fileIO
m_indexing
m_random
m_readline
m_strings
m_writeline
m_time
m_allocate
m_reallocate
m_copy
m_sort
m_select
m_maths
m_searching
Stopwatch_Class
ProgressBar_Class
m_KdTree
Test program for the coretran library
Calls
Variables
fName sa cTest lTest iTest istat N nIterations ar br cr ar1D br1D cr1D ar2D br2D ar3D br3D a b c a1D b1D c1D a2D b2D a3D b3D ia ib ic id ie ia1D ib1D ic1D ia2D ib2D ia3D ib3D iad ibd icd iad1D ibd1D icd1D iad2D ibd2D iad3D ibd3D x y z za1D zb1D za2D zb2D za3D zb3D zza1D zzb1D zza2D zzb2D zza3D zzb3D la lb lc la1D lb1D la2D lb2D la3D lb3D passCount testTotal clk P tree search iunit maxSize nSizes sizes times
Subroutines
test
Variables
Type Attributes Name Initial
character(len=100) :: fName
character(len=128) :: sa
character(len=:), allocatable :: cTest
logical :: lTest
integer(kind=i32) :: iTest
integer(kind=i32) :: istat
integer(kind=i32) :: N
integer(kind=i32) :: nIterations
real(kind=r32) :: ar
real(kind=r32) :: br
real(kind=r32) :: cr
real(kind=r32), allocatable :: ar1D(:)
real(kind=r32), allocatable :: br1D(:)
real(kind=r32), allocatable :: cr1D(:)
real(kind=r32), allocatable :: ar2D(:,:)
real(kind=r32), allocatable :: br2D(:,:)
real(kind=r32), allocatable :: ar3D(:,:,:)
real(kind=r32), allocatable :: br3D(:,:,:)
real(kind=r64) :: a
real(kind=r64) :: b
real(kind=r64) :: c
real(kind=r64), allocatable :: a1D(:)
real(kind=r64), allocatable :: b1D(:)
real(kind=r64), allocatable :: c1D(:)
real(kind=r64), allocatable :: a2D(:,:)
real(kind=r64), allocatable :: b2D(:,:)
real(kind=r64), allocatable :: a3D(:,:,:)
real(kind=r64), allocatable :: b3D(:,:,:)
integer(kind=i32) :: ia
integer(kind=i32) :: ib
integer(kind=i32) :: ic
integer(kind=i32) :: id
integer(kind=i32) :: ie
integer(kind=i32), allocatable :: ia1D(:)
integer(kind=i32), allocatable :: ib1D(:)
integer(kind=i32), allocatable :: ic1D(:)
integer(kind=i32), allocatable :: ia2D(:,:)
integer(kind=i32), allocatable :: ib2D(:,:)
integer(kind=i32), allocatable :: ia3D(:,:,:)
integer(kind=i32), allocatable :: ib3D(:,:,:)
integer(kind=i64) :: iad
integer(kind=i64) :: ibd
integer(kind=i64) :: icd
integer(kind=i64), allocatable :: iad1D(:)
integer(kind=i64), allocatable :: ibd1D(:)
integer(kind=i64), allocatable :: icd1D(:)
integer(kind=i64), allocatable :: iad2D(:,:)
integer(kind=i64), allocatable :: ibd2D(:,:)
integer(kind=i64), allocatable :: iad3D(:,:,:)
integer(kind=i64), allocatable :: ibd3D(:,:,:)
complex(kind=r32) :: x
complex(kind=r32) :: y
complex(kind=r32) :: z
complex(kind=r32), allocatable :: za1D(:)
complex(kind=r32), allocatable :: zb1D(:)
complex(kind=r32), allocatable :: za2D(:,:)
complex(kind=r32), allocatable :: zb2D(:,:)
complex(kind=r32), allocatable :: za3D(:,:,:)
complex(kind=r32), allocatable :: zb3D(:,:,:)
complex(kind=r64), allocatable :: zza1D(:)
complex(kind=r64), allocatable :: zzb1D(:)
complex(kind=r64), allocatable :: zza2D(:,:)
complex(kind=r64), allocatable :: zzb2D(:,:)
complex(kind=r64), allocatable :: zza3D(:,:,:)
complex(kind=r64), allocatable :: zzb3D(:,:,:)
logical :: la
logical :: lb
logical :: lc
logical, allocatable :: la1D(:)
logical, allocatable :: lb1D(:)
logical, allocatable :: la2D(:,:)
logical, allocatable :: lb2D(:,:)
logical, allocatable :: la3D(:,:,:)
logical, allocatable :: lb3D(:,:,:)
integer(kind=i32) :: passCount = 0
integer(kind=i32) :: testTotal = 0
type(Stopwatch) :: clk
type(ProgressBar) :: P
type(KdTree) :: tree
type(KdTreeSearch) :: search
integer(kind=i32) :: iunit
integer(kind=i32) :: maxSize = 25
integer(kind=i32), parameter :: nSizes = 6
integer(kind=i32) :: sizes(nSizes)
real(kind=r64) :: times(nSizes)
Subroutines
subroutine test(l, msg)
Arguments
Type Intent Optional Attributes Name
logical :: l
character(len=*) :: msg
All Programs
scaleTest_coretran test_coretran
Call graph
scaletest_coretran calls str, closefile, rngnormal, sort, msg, kdtree, binarysearch, openfile, setprng, rnginteger
rngnormal calls rngnormal_d1, rngnormal_d2d, rngnormal_d3d, rngnormal_d1d
setprng calls setprng_withseed, setprng_woseed
rnginteger calls rnginteger_i1, rnginteger_i2d, rnginteger_i1d, rnginteger_i3d
setprng_withseed calls prng
setprng_woseed calls prng