test_coretran – Fortran Program
test_coretran Program
60 statements
Source File
Uses:
m_unitTester
iso_fortran_env
variableKind
m_random
m_tests
Test program for the coretran library
Calls
Variables
test sa i iTest istat N nIterations
Variables
Type Attributes Name Initial
type(tester) :: test
character(len=cLen) :: sa
integer(kind=i32) :: i
integer(kind=i32) :: iTest
integer(kind=i32) :: istat
integer(kind=i32) :: N
integer(kind=i32) :: nIterations
All Programs
scaleTest_coretran test_coretran
Call graph
test_coretran calls rargdynamicarray_test, random_test, emsg, indexing_test, prng_test, copy_test, iargdynamicarray_test, strings_test, array1d_test, rdynamicarray_test, kdtree_test, fileio_test, dargdynamicarray_test, time_test, msg, idynamicarray_test, ddynamicarray_test, setprng, allocate_test, maths_test, idargdynamicarray_test, select_test, reallocate_test, sorting_test, iddynamicarray_test
rargdynamicarray_test calls rargdynamicarray, msg
random_test calls msg, str, prng
indexing_test calls msg, sub2ind, ind2sub
prng_test calls prng, omp_get_num_threads, omp_get_thread_num, getrandomseed
copy_test calls msg, copy
iargdynamicarray_test calls msg, iargdynamicarray
strings_test calls msg, str, isstring, countentries, read1integer, uppercase, prependstring, lowercase, hasnentries, appendstring, compact, removecomments, replacedelim
array1d_test calls msg, diff, arange
rdynamicarray_test calls msg, rdynamicarray
kdtree_test calls msg, arange, rngnormal, argsort, idynamicarray, kdtree
dargdynamicarray_test calls msg, dargdynamicarray
time_test calls msg, rngnormal, daysinmonth, timeinseconds, secondstohms, isleapyear, daysinyear, progressbar
idynamicarray_test calls idynamicarray
ddynamicarray_test calls ddynamicarray
setprng calls setprng_withseed, setprng_woseed
allocate_test calls msg
maths_test calls msg, arange, normi, crossproduct, norm1, cumprod, twosum, fasttwosum, median, variance, geometricmean, mean, cumsum, project, std
idargdynamicarray_test calls msg, idargdynamicarray
select_test calls msg, arange, rngnormal, argselect, rnginteger, sort
reallocate_test calls msg, reallocate
sorting_test calls msg, str, arange, rngnormal, argsort, rnginteger, sort, issorted
iddynamicarray_test calls iddynamicarray
isstring calls lowercase
countentries calls compact
read1integer calls compact
hasnentries calls countentries
replacedelim calls emsg
daysinmonth calls isleapyear
daysinyear calls isleapyear
setprng_withseed calls prng
setprng_woseed calls prng