closeFile – Fortran Program
closeFile Subroutine
17 statements
Source File
public subroutine closeFile(fname, iunit, stat, istat)
Close a file and perform any necessary checks
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
File name
integer(kind=i32), intent(in) :: iunit
Unit number returned
character(len=*), intent(in) :: stat
Status of the file you are closing
integer(kind=i32), intent(out) :: istat
Error Flag
Calls
Called By
All Procedures
allocate allocate_test appendString arange argInsertionsort argMedianOf3 argPartition argSelect argSort binarySearch checkIsOpen closeFile compact compare compare_d1 copy countEntries crossproduct cumprod cumsum dArgDynamicArray daysInMonth daysInYear dDynamicArray deallocate debug debug_s deleteFile diff eMsg fastTwoDiff fastTwoSum fErr fileExists geometricMean getExtension getFileSize getNFileLines getRandomSeed hasExtension hasNentries iachar1D iArgDynamicArray idArgDynamicArray idDynamicArray iDynamicArray ind2sub insertAt__idDynamicArray insertAt__iDynamicArray insertAt__rDynamicArray insertionsort integerBin intervalSearch isLeapYear isOpen isOpen_i1 isOpen_s isSorted isString KdTree lowerCase mean median medianOf3 mErr msg norm1 normI openBinaryFile openFile partition partition3way partition3way_d1D prependString Prng ProgressBar project rArgDynamicArray rDynamicArray read1Dble read1Integer readline readline reallocate removeComments repeat replacedelim rngExponential rngExponential_d1 rngExponential_d1D rngExponential_d2D rngExponential_d3D rngExponential_unscaled_d1 rngInteger rngInteger_i1 rngInteger_i1D rngInteger_i2D rngInteger_i3D rngNormal rngNormal_d1 rngNormal_d1D rngNormal_d2D rngNormal_d3D rngUniform rngUniform_d1 rngUniform_d1D rngUniform_d2D rngUniform_d3D rngUniform_xorshift rngWeibull rngWeibull_d1 rngWeibull_d1D rngWeibull_d2D rngWeibull_d3D secondsToHMS select setPrng setPrng_withSeed setPrng_WOseed shuffle simpleSearch skipFileLines sort std str sub2ind swap tester timeInSeconds timeToInteger trimExtension trimmedmean twoDiff twoSum upperCase variance wMsg writeline
Call graph
closefile calls compact, ferr, lowercase
getnfilelines calls closefile