msg – Fortran Program
msg Subroutine
10 statements
Source File
public subroutine msg(aMsg, iunit)
Write a message
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: aMsg
Message to write
integer(kind=i32), intent(in), optional :: iunit
file id to write the message to
Called By
All Procedures
allocate allocate_test appendString arange argInsertionsort argMedianOf3 argPartition argSelect argSort array1D_test binarySearch checkIsOpen closeFile compact compare compare_d1 copy copy_test countEntries crossproduct cumprod cumsum dArgDynamicArray dArgDynamicArray_test daysInMonth daysInYear dDynamicArray dDynamicArray_test deallocate debug debug_s deleteFile diff eMsg fastTwoDiff fastTwoSum fErr fileExists fileIO_test geometricMean getExtension getFileSize getNFileLines getRandomSeed hasExtension hasNentries iachar1D iArgDynamicArray iArgDynamicArray_test idArgDynamicArray idArgDynamicArray_test idDynamicArray idDynamicArray_test iDynamicArray iDynamicArray_test ind2sub indexing_test insertionsort integerBin intervalSearch isLeapYear isOpen isSorted isString KdTree KdTree_test lowerCase maths_test mean median medianOf3 mErr msg norm1 normI openBinaryFile openFile partition partition3way partition3way_d1D prependString Prng Prng_test ProgressBar project random_test rArgDynamicArray rArgDynamicArray_test rDynamicArray rDynamicArray_test read1Dble read1Integer readline readline reallocate reallocate_test removeComments repeat replacedelim rngExponential rngExponential_d1 rngExponential_d1D rngExponential_d2D rngExponential_d3D rngExponential_unscaled_d1 rngInteger rngInteger_i1 rngInteger_i1D rngInteger_i2D rngInteger_i3D rngNormal rngNormal_d1 rngNormal_d1D rngNormal_d2D rngNormal_d3D rngUniform rngUniform_d1 rngUniform_d1D rngUniform_d2D rngUniform_d3D rngUniform_xorshift rngWeibull rngWeibull_d1 rngWeibull_d1D rngWeibull_d2D rngWeibull_d3D secondsToHMS select select_test setPrng setPrng_withSeed setPrng_WOseed shuffle simpleSearch skipFileLines sort sorting_test std str strings_test sub2ind swap test tester time_test timeInSeconds timeToInteger trimExtension trimmedmean twoDiff twoSum upperCase variance wMsg writeline
Call graph
scaletest_coretran calls msg
time_test calls msg
iargdynamicarray_test calls msg
maths_test calls msg
rargdynamicarray_test calls msg
wmsg calls msg
select_test calls msg
strings_test calls msg
random_test calls msg
reallocate_test calls msg
array1d_test calls msg
indexing_test calls msg
idargdynamicarray_test calls msg
rdynamicarray_test calls msg
sorting_test calls msg
emsg calls msg
kdtree_test calls msg
dargdynamicarray_test calls msg
copy_test calls msg
allocate_test calls msg
test_coretran calls time_test, iargdynamicarray_test, maths_test, rargdynamicarray_test, select_test, strings_test, random_test, reallocate_test, array1d_test, indexing_test, idargdynamicarray_test, rdynamicarray_test, sorting_test, kdtree_test, dargdynamicarray_test, copy_test, allocate_test
ferr calls emsg
merr calls emsg