compare – Fortran Program
compare Interface
3 statements
Source File
public interface compare
Calls
Called By
Module Procedures
compare_d1
Module Procedures
public function compare_d1(this, that) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=r64) :: this
real(kind=r64) :: that
Return Value integer(kind=i32)
All Procedures
absTimetoHMS allocate allocate_test appendString arange argInsertionsort argMedianOf3 argPartition argSelect argSort array1D_test binarySearch checkIsOpen closeFile compact compare compare_d1 copy copy_test countEntries crossproduct cumprod cumsum dArgDynamicArray dArgDynamicArray_test daysinMonth daysinYear dDynamicArray dDynamicArray_test deallocate debug debug_s deleteFile diff eMsg fastTwoDiff fastTwoSum fErr fileExists fileIO_test geometricMean getExtension getFileSize getNFileLines hasExtension hasNentries iachar1D iArgDynamicArray iArgDynamicArray_test idArgDynamicArray idArgDynamicArray_test idDynamicArray idDynamicArray_test iDynamicArray iDynamicArray_test ind2sub indexing_test insertAt__idDynamicArray insertAt__iDynamicArray insertAt__rDynamicArray insertionsort integerBin intervalSearch isLeapYear isOpen isSorted isString KdTree lowerCase maths_test mean median medianOf3 mErr msg norm1 normI openBinaryFile openFile partition partition3way partition3way_d1D prependString ProgressBar project random_test rArgDynamicArray rArgDynamicArray_test rDynamicArray rDynamicArray_test read1Dble read1Integer readline readline reallocate reallocate_test removeComments repeat replacedelim rngChisq rngExponential rngGamma rngInteger rngNormal rngUniform rngWeibull select select_test setRNG shuffle simpleSearch skipFileLines sort sorting_test std str strings_test sub2ind swap tester time_test timeinseconds trimExtension trimmedmean twoDiff twoSum upperCase variance wMsg writeline
Call graph
compare calls compare_d1
partition3way_d1d calls compare
partition3way calls partition3way_d1d