str – Fortran Program
str Interface
8 statements
Source File
public interface str
Interface to print a string representation of a number The output format options can be set using the printOptions class
Example usage
use variableKind
use m_strings
real(r64) :: arr(20)
integer(i32) :: i
integer(i32) :: j(5)
arr = [(dble(i), i = 1,20)]
i = 12
j = [0, 1, 2, 3, 4]
write(*,'(a)') str(i)//str(j)
write(*,'(a)') str(j)//str(arr)
write(*,'(a)') str(arr)
printOptions%threshold = 0
write(*,'(a)') str(arr)
Called By
Module Procedures
str_r1 str_r1D str_d1 str_d1D str_d2D str_i1 str_i1D str_id1 str_id1D str_s1 str_s1D str_1L
Module Procedures
private function str_r1(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
real(kind=r32), intent(in) :: this
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_r1D(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
real(kind=r32), intent(in) :: this(:)
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_d1(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
real(kind=r64), intent(in) :: this
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_d1D(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
real(kind=r64), intent(in) :: this(:)
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_d2D(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
real(kind=r64), intent(in) :: this(:,:)
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_i1(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
integer(kind=i32), intent(in) :: this
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_i1D(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
integer(kind=i32), intent(in) :: this(:)
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_id1(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
integer(kind=i64), intent(in) :: this
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_id1D(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
integer(kind=i64), intent(in) :: this(:)
1D array
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_s1(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: this
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_s1D(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: this(:)
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
private function str_1L(this, delim) result(res)
Interfaced with str()
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: this
character(len=*), intent(in), optional :: delim
Return Value character(len=:), allocatable
All Procedures
allocate allocate_test appendString arange argInsertionsort argMedianOf3 argPartition argSelect argSort array1D_test binarySearch checkIsOpen closeFile compact compare compare_d1 copy copy_test countEntries crossproduct cumprod cumsum dArgDynamicArray dArgDynamicArray_test daysInMonth daysInYear dDynamicArray dDynamicArray_test deallocate debug debug_s deleteFile diff eMsg fastTwoDiff fastTwoSum fErr fileExists fileIO_test geometricMean getExtension getFileSize getNFileLines getRandomSeed hasExtension hasNentries iachar1D iArgDynamicArray iArgDynamicArray_test idArgDynamicArray idArgDynamicArray_test idDynamicArray idDynamicArray_test iDynamicArray iDynamicArray_test ind2sub indexing_test insertionsort integerBin intervalSearch isLeapYear isOpen isSorted isString KdTree KdTree_test lowerCase maths_test mean median medianOf3 mErr msg norm1 normI openBinaryFile openFile partition partition3way partition3way_d1D prependString Prng Prng_test ProgressBar project random_test rArgDynamicArray rArgDynamicArray_test rDynamicArray rDynamicArray_test read1Dble read1Integer readline readline reallocate reallocate_test removeComments repeat replacedelim rngExponential rngExponential_d1 rngExponential_d1D rngExponential_d2D rngExponential_d3D rngExponential_unscaled_d1 rngInteger rngInteger_i1 rngInteger_i1D rngInteger_i2D rngInteger_i3D rngNormal rngNormal_d1 rngNormal_d1D rngNormal_d2D rngNormal_d3D rngUniform rngUniform_d1 rngUniform_d1D rngUniform_d2D rngUniform_d3D rngUniform_xorshift rngWeibull rngWeibull_d1 rngWeibull_d1D rngWeibull_d2D rngWeibull_d3D secondsToHMS select select_test setPrng setPrng_withSeed setPrng_WOseed shuffle simpleSearch skipFileLines sort sorting_test std str strings_test sub2ind swap test tester time_test timeInSeconds timeToInteger trimExtension trimmedmean twoDiff twoSum upperCase variance wMsg writeline
Call graph
scaletest_coretran calls str
strings_test calls str
random_test calls str
debug_s calls str
sorting_test calls str
read1dble calls str
test_coretran calls strings_test, random_test, sorting_test